logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: INFO

spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/order/**, /api/v1/order, /api/v1/station/**, /api/v1/station
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/user/**, /api/v1/user
          filters: